title: ROS2 Publisher/Subscriber Practice
description: `키보드 입력(`w a s d`)을 받아 `cmd_vel` 토픽을 발행하고 turtlesim 거북이를 실시간으로 조종한다.
tags:
  - ros2
  - beginner
  - pubsub
status: done


# status: planning
# status: in progress
# status: done
